spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mall
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Use H2Dialect for H2 database
        format_sql: true

    logging:
      level:
        org.hibernate.SQL: debug
